# Codecov Configuration
# See https://docs.codecov.io/docs/codecov-yaml for reference

codecov:
  require_ci_to_pass: true
  max_report_age: false # Disable report age check to prevent "exceeds max age" errors

# Path fixing: Coverage runs from backend/ directory, so paths in coverage.xml
# are relative to backend/ (e.g., "main.py"). We need to prepend "backend/"
# so Codecov can map them to the repo structure (e.g., "backend/main.py").
fixes:
  - "::backend/" # Prepend "backend/" to all paths

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 70%
        threshold: 5%
        informational: false

    patch:
      default:
        target: 70%
        threshold: 5%

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

flags:
  backend-unit:
    paths:
      - backend/
    carryforward: true

  backend-integration:
    paths:
      - backend/
    carryforward: true

  frontend:
    paths:
      - frontend/src/
    carryforward: true

ignore:
  - "**/__pycache__/**"
  - "**/node_modules/**"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/test/**"
  - "**/tests/**"
  - "**/*.config.*"
  - "**/migrations/**"
